### ISSUE TITLE
Automated release explanation

### ISSUE THREAD

**Issue by semoal** [lingui/codemods#3]
### How does it works?

`semantic-release` package contains all the necessary actions to:

- `@semantic-release/commit-analyzer`: Will analyze all the commits since the latest tagged release and will detect what version needs to be increased to match the commits spec.
For example of commits and his response:
  - `fix(): commit` : x.x.1 - Patch
  - `feat(): commit` : x.1.x - Feature
  - `perf(pencil): remove graphiteWidth option

    BREAKING CHANGE: The graphiteWidth option has been removed.
    The default graphite width of 10mm is always used for performance reasons.
    ` : 1.x.x - Breaking change

- `@semantic-release/release-notes-generator`: Generate release notes for the commits added since the last release with conventional-changelog
- `@semantic-release/changelog`: Create or update the changelog file in the local project repository
- `@semantic-release/npm`: Publish the package on the npm registry
- `@semantic-release/git`: Push a release commit and tag, including configurable files
- `@semantic-release/github`: Publish a GitHub release

### What's the best strategy?

All the pull requests merged should be merged following the conventional-commits standard in that way we'll create a history since the latest release. (if some user is not following the standard is a best practice to squash merge to overwrite the pull request history, and add a new commit name)

So when we're ready to deploy our version we just have to move up to Github Actions tab and deploy manually the version.

<img width="972" alt="Screenshot 2020-10-26 at 12 37 44" src="https://user-images.githubusercontent.com/22656541/97168097-2b0a0480-1788-11eb-8c19-98b1606b7db4.png">
<img width="367" align="right" alt="Screenshot 2020-10-26 at 12 37 48" src="https://user-images.githubusercontent.com/22656541/97168093-29d8d780-1788-11eb-9767-498955398691.png">

### What happens once we triggered that manual action?

`yarn release` will be executed and of course all the above steps mentioned.

Will publish to npm the package, create a CHANGELOG.md, update the package.json version, create a git tag, and a commit with all the changes since the latest release (changelog, package.json..)

If some user has specified that some commit fixes any issue and in the commit appears the id of the issue, automatically semantic-release-bot will close that issue 🆒 

### Examples

I use this strategy on big libraries like http://github.com/rematch/rematch/, and other tiny libraries like https://github.com/semoal/themeprovider-storybook, and for me fits perfectly =)

### Pending tasks

- [x] Create a secret on project settings with a valid npm token to publish to npm.  **(I can't do it by permissions, can't access to project settings)**
```bash
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

**Comment by semoal** [comment]
@tricoder42 :)

**Comment by tricoder42** [comment]
Love it! Do you need anything from here or are you able to set it up completely?

Also, once finishes, we could probably do the same in the main `js-lingui` repository. How this process handles pre-releases? For example, anything from `next` is published as pre-release?

**Comment by semoal** [comment]
i've need access to project settings to add a npm token to publish, or if you can add it feel free.

About js-lingui absolutly once i got some free time I'll create a pull request to js-lingui, manual action is cool because request a text on Rematch i have a validation if we introduce `latest` it deploys to `latest` npm tag, if we write `next` it's released as pre-release on Github and npm, so yes, it handles pre-releases =)

**Comment by tricoder42** [comment]
> i've need access to project settings to add a npm token to publish, or if you can add it feel free.

I've just added `NPM_TOKEN`. Please check if it works (it shouldn't require 2FA)

> On next branch, automatically fills up that tag to next, on main/master branch latest

Amazing™️

**Comment by semoal** [comment]
```bash
[12:40:05 PM] [semantic-release] › ✖  Failed step "fail" of plugin "@semantic-release/github"
[12:40:05 PM] [semantic-release] › ✖  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (semantic-release/github@master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository lingui/codemods.

[12:40:05 PM] [semantic-release] › ✖  EGITNOPERMISSION Cannot push to the Git repository.
semantic-release cannot push the version tag to the branch main on the remote Git repository with URL lingui/codemods.git.

This can be caused by:

    * a misconfiguration of the repositoryUrl (semantic-release/semantic-release@master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (semantic-release/semantic-release@master/docs/usage/ci-configuration.md#authentication)

SemanticReleaseError: Cannot push to the Git repository.
```

I need one more thing of you Tomáš sorry, you need to add another secret GH_TOKEN, with a  Github personal access_token to be able to do a release on github from cli =)

**Comment by tricoder42** [comment]
@semoal Try now please

**Comment by semoal** [comment]
@tricoder42 as you see the ci failed with a invalid npm token and the bot automatically created an issue with all the details :)

**Comment by semoal** [comment]
Done =) All setup mate 👍🏻

**Comment by tricoder42** [comment]
Cool! The NPM auth token doesn't work as expected — they offer `automation` auth token, which should bypass 2FA settings, but obviously it doesn't work. I had to disable 2FA and create a regular `publish` token.

**Comment by semoal** [comment]
Great, I'll setup all this things on js-lingui in a few days :)
Glad that i could help on js-lingui 👍🏻

**Comment by tricoder42** [comment]
Thanks a lot! You've really helped me a lot! I'm hoping to finish last remaining tasks in few days and finally release it
